msgid ""
msgstr "Project-Id-Version: pyload\n"
"Report-Msgid-Bugs-To: 'bugs@pyload.org'\n"
"POT-Creation-Date: 2014-04-08 15:01+0200\n"
"PO-Revision-Date: 2014-04-09 05:39-0400\n"
"Last-Translator: pyloadTeam <team@pyload.org>\n"
"Language-Team: Japanese\n"
"Language: ja_JP\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: crowdin.net\n"

#: pyload/Core.py:182
msgid "Received Quit signal"
msgstr "終了のシグナルを受信"

#: pyload/Core.py:303
#, python-format
msgid "pyLoad already running with pid %s"
msgstr "pyLoad はプロセス ID %s で既に実行中"

#: pyload/Core.py:317
#, python-format
msgid "Failed changing group: %s"
msgstr "グループの変更に失敗しました: %s"

#: pyload/Core.py:327
#, python-format
msgid "Failed changing user: %s"
msgstr "ユーザーの変更に失敗しました: %s"

#: pyload/Core.py:329
msgid "folder for logs"
msgstr "ログのフォルダ"

#: pyload/Core.py:340
msgid "Starting"
msgstr "開始中"

#: pyload/Core.py:341
#, python-format
msgid "Using home directory: %s"
msgstr "ホームディレクトリとして %s を使用中"

#: pyload/Core.py:350
msgid "pycrypto to decode container files"
msgstr ""

#: pyload/Core.py:353
msgid "folder for temporary files"
msgstr "一時ファイルのフォルダ"

#: pyload/Core.py:358
msgid "folder for downloads"
msgstr "ダウンロード先のフォルダ"

#: pyload/Core.py:361
msgid "OpenSSL for secure connection"
msgstr "セキュアな接続のための OpenSSL"

#: pyload/Core.py:365
msgid "Moving old user config to DB"
msgstr ""

#: pyload/Core.py:368
msgid "Please check your logindata with ./pyload.py -u"
msgstr "./pyload.py -u であなたのログインデータをチェックしてください"

#: pyload/Core.py:371
msgid "All links removed"
msgstr "すべてのリンクが削除されました"

#: pyload/Core.py:402
#, python-format
msgid "Downloadtime: %s"
msgstr "ダウンロード時間: %s"

#: pyload/Core.py:412
#, python-format
msgid "Free space: %s"
msgstr "空き領域: %s"

#: pyload/Core.py:432
msgid "Activating Accounts..."
msgstr "アカウントをアクティベート中..."

#: pyload/Core.py:438
msgid "Activating Plugins..."
msgstr "プラグインをアクティベート中..."

#: pyload/Core.py:441
msgid "pyLoad is up and running"
msgstr "pyLoad が実行中"

#: pyload/Core.py:460
msgid "restarting pyLoad"
msgstr "pyLoad を再起動中"

#: pyload/Core.py:464
msgid "pyLoad quits"
msgstr "pyLoad が終了します"

#: pyload/Core.py:521
#, python-format
msgid "Install %s"
msgstr "%s をインストール"

#: pyload/Core.py:557
#, python-format
msgid "could not find %(desc)s: %(name)s"
msgstr ""

#: pyload/Core.py:559
#, python-format
msgid "could not create %(desc)s: %(name)s"
msgstr ""

#: pyload/Core.py:580
msgid "shutting down..."
msgstr "シャットダウン中..."

#: pyload/Core.py:597
msgid "error while shutting down"
msgstr "シャットダウン中にエラー"

#: pyload/Core.py:661
msgid "killed pyLoad from Terminal"
msgstr ""

#: pyload/database/DatabaseBackend.py:174
msgid "Filedatabase was deleted due to incompatible version."
msgstr ""

#: pyload/database/DatabaseBackend.py:189
msgid "Filedatabase could NOT be converted."
msgstr ""

#: pyload/database/DatabaseBackend.py:198
msgid "Database was converted from v2 to v3."
msgstr ""

#: pyload/database/DatabaseBackend.py:206
msgid "Database was converted from v3 to v4."
msgstr ""

#: pyload/database/DatabaseBackend.py:252
msgid "Converting old Django DB"
msgstr ""

#: pyload/database/FileDatabase.py:45
msgid "finished"
msgstr "完了"

#: pyload/database/FileDatabase.py:45
msgid "offline"
msgstr "オフライン"

#: pyload/database/FileDatabase.py:45
msgid "online"
msgstr "オンライン"

#: pyload/database/FileDatabase.py:45
msgid "queued"
msgstr "キューに入っています。"

#: pyload/database/FileDatabase.py:45
msgid "skipped"
msgstr "スキップ"

#: pyload/database/FileDatabase.py:45
msgid "waiting"
msgstr "待機中"

#: pyload/database/FileDatabase.py:45
msgid "temp. offline"
msgstr "一時的にオフライン"

#: pyload/database/FileDatabase.py:45
msgid "starting"
msgstr "開始中"

#: pyload/database/FileDatabase.py:45
msgid "failed"
msgstr "失敗しました"

#: pyload/database/FileDatabase.py:45
msgid "aborted"
msgstr "中止しました"

#: pyload/database/FileDatabase.py:45
msgid "decrypting"
msgstr "復号化"

#: pyload/database/FileDatabase.py:45
msgid "custom"
msgstr "カスタム"

#: pyload/database/FileDatabase.py:45
msgid "downloading"
msgstr "ダウンロード中"

#: pyload/database/FileDatabase.py:45
msgid "processing"
msgstr "処理中"

#: pyload/database/FileDatabase.py:45
msgid "unknown"
msgstr "不明"

#: pyload/database/FileDatabase.py:531 pyload/plugins/addon/IRCInterface.py:74
#: pyload/plugins/addon/XMPPInterface.py:83
#, python-format
msgid "Package finished: %s"
msgstr "パッケージが完了しました: %s"

#: pyload/remote/ThriftBackend.py:39
msgid "Using SSL ThriftBackend"
msgstr ""

#: pyload/manager/RemoteManager.py:35
#, python-format
msgid "Remote backend error: %s"
msgstr "リモート バックエンド エラー: %s"

#: pyload/manager/RemoteManager.py:82
#, python-format
msgid "Starting %(name)s: %(addr)s:%(port)s"
msgstr "開始 %(name)s：%(addr)s：%(port)s"

#: pyload/manager/RemoteManager.py:84
#, python-format
msgid "Failed loading backend %(name)s | %(error)s"
msgstr " バックエンド %(name)sの読み込みに失敗した |%(error)s"

#: pyload/web/json_app.py:57
#, python-format
msgid "waiting %s"
msgstr "%s を待機中"

#: pyload/thread/ServerThread.py:35
msgid "SSL certificates not found."
msgstr "SSL 証明書が見つかりません。"

#: pyload/thread/ServerThread.py:39
#, python-format
msgid "Sorry, we dropped support for starting %s directly within pyLoad"
msgstr ""

#: pyload/thread/ServerThread.py:40
msgid "You can use the threaded server which offers good performance and ssl,"
msgstr ""

#: pyload/thread/ServerThread.py:41
#, python-format
msgid "of course you can still use your existing %s with pyLoads fastcgi server"
msgstr ""

#: pyload/thread/ServerThread.py:42
msgid "sample configs are located in the pyload/web/servers directory"
msgstr ""

#: pyload/thread/ServerThread.py:49
#, python-format
msgid "Can't use %(server)s, python-flup is not installed!"
msgstr ""

#: pyload/thread/ServerThread.py:56
#, python-format
msgid "Error importing lightweight server: %s"
msgstr ""

#: pyload/thread/ServerThread.py:57
msgid "You need to download and compile bjoern, https://github.com/jonashaag/bjoern"
msgstr ""

#: pyload/thread/ServerThread.py:58
msgid "Copy the boern.so to pyload/lib folder or use Setup.py install"
msgstr ""

#: pyload/thread/ServerThread.py:59
msgid "Of course you need to be familiar with linux and know how to compile software"
msgstr ""

#: pyload/thread/ServerThread.py:63
msgid "Server set to threaded, due to known performance problems on windows."
msgstr ""

#: pyload/thread/ServerThread.py:80 pyload/thread/ServerThread.py:103
msgid "This server offers no SSL, please consider using threaded instead"
msgstr "このサーバーで SSL はありません、代わりにスレッドを使用してください"

#: pyload/thread/ServerThread.py:82
#, python-format
msgid "Starting builtin webserver: %(host)s:%(port)d"
msgstr ""

#: pyload/thread/ServerThread.py:87
#, python-format
msgid "Starting threaded SSL webserver: %(host)s:%(port)d"
msgstr ""

#: pyload/thread/ServerThread.py:91
#, python-format
msgid "Starting threaded webserver: %(host)s:%(port)d"
msgstr ""

#: pyload/thread/ServerThread.py:97
#, python-format
msgid "Starting fastcgi server: %(host)s:%(port)d"
msgstr ""

#: pyload/thread/ServerThread.py:105
#, python-format
msgid "Starting lightweight webserver (bjoern): %(host)s:%(port)d"
msgstr ""

#: pyload/web/pyload_app.py:125
msgid "You dont have permission to access this page."
msgstr ""

#: pyload/web/pyload_app.py:193
msgid "Download directory not found."
msgstr ""

#: pyload/web/pyload_app.py:260 pyload/web/pyload_app.py:267
msgid "unlimited"
msgstr "無制限"

#: pyload/web/pyload_app.py:262 pyload/web/pyload_app.py:269
msgid "not available"
msgstr "利用不可"

#: pyload/web/pyload_app.py:508
msgid "Run pyload.py -s to access the setup."
msgstr ""

#: pyload/network/HTTPDownload.py:245
#, python-format
msgid "Download chunks failed, fallback to single connection | %s"
msgstr "ダウンロード チャンクへの移行に失敗しました 1 つの接続 |。%s"

#: pyload/thread/PluginThread.py:183
#, python-format
msgid "Download starts: %s"
msgstr "ダウンロード開始: %s"

#: pyload/thread/PluginThread.py:189
#, python-format
msgid "Download finished: %s"
msgstr "ダウンロード完了: %s"

#: pyload/thread/PluginThread.py:194 pyload/thread/PluginThread.py:365
#, python-format
msgid "Plugin %s is missing a function."
msgstr "プラグイン %s には関数がありません。"

#: pyload/thread/PluginThread.py:202 pyload/thread/PluginThread.py:265
#: pyload/thread/PluginThread.py:382
#, python-format
msgid "Download aborted: %s"
msgstr "ダウンロードを中止: %s"

#: pyload/thread/PluginThread.py:222
#, python-format
msgid "Download restarted: %(name)s | %(msg)s"
msgstr "ダウンロードを再開: %(name)s | %(msg)s"

#: pyload/thread/PluginThread.py:231 pyload/thread/PluginThread.py:373
#, python-format
msgid "Download is offline: %s"
msgstr "ダウンロードがオフライン: %s"

#: pyload/thread/PluginThread.py:234
#, python-format
msgid "Download is temporary offline: %s"
msgstr "ダウンロードが一時的にオフライン: %s"

#: pyload/thread/PluginThread.py:237 pyload/thread/PluginThread.py:304
#, python-format
msgid "Download failed: %(name)s | %(msg)s"
msgstr "ダウンロードに失敗しました: %(name)s|%(msg)s"

#: pyload/thread/PluginThread.py:254
msgid "Couldn't connect to host or connection reset, waiting 1 minute and retry."
msgstr "ホストまたは接続のリセットに接続できなかったため、1 分後接続に再試行してください。"

#: pyload/thread/PluginThread.py:290
#, python-format
msgid "Download skipped: %(name)s due to %(plugin)s"
msgstr "ダウンロードをスキップしました:%(plugin)sにより %(name)s"

#: pyload/thread/PluginThread.py:361
#, python-format
msgid "Decrypting starts: %s"
msgstr ""

#: pyload/thread/PluginThread.py:376 pyload/thread/PluginThread.py:394
#, python-format
msgid "Decrypting failed: %(name)s | %(msg)s"
msgstr ""

#: pyload/thread/PluginThread.py:388
#, python-format
msgid "Retrying %s"
msgstr ""

#: pyload/thread/PluginThread.py:635
#, python-format
msgid "Info Fetching for %(name)s failed | %(err)s"
msgstr "%(name)sの失敗の情報取得する |%(err)s"

#: pyload/manager/AddonManager.py:90 pyload/plugins/Addon.py:102
#, python-format
msgid "Error executing addon: %s"
msgstr ""

#: pyload/manager/AddonManager.py:140
#, python-format
msgid "Failed activating %(name)s"
msgstr "%(name)sをアクティブ に失敗しました"

#: pyload/manager/AddonManager.py:144
#, python-format
msgid "Activated plugins: %s"
msgstr ""

#: pyload/manager/AddonManager.py:145
#, python-format
msgid "Deactivate plugins: %s"
msgstr ""

#: pyload/manager/ThreadManager.py:137
#, python-format
msgid "Reconnect Failed: %s"
msgstr "再接続に失敗しました: %s"

#: pyload/manager/ThreadManager.py:176
msgid "Reconnect script not found!"
msgstr "再接続スクリプトが見つかりません!"

#: pyload/manager/ThreadManager.py:182
msgid "Starting reconnect"
msgstr "再接続を開始中"

#: pyload/manager/ThreadManager.py:196
msgid "Failed executing reconnect script!"
msgstr "失敗した実行スクリプト再接続 ！"

#: pyload/manager/ThreadManager.py:208
#, python-format
msgid "Reconnected, new IP: %s"
msgstr "再接続、新しい IP: %s"

#: pyload/manager/ThreadManager.py:288
msgid "Not enough space left on device"
msgstr "デバイスに空き領域不足"

#: pyload/plugins/Account.py:85 pyload/plugins/Account.py:91
#, python-format
msgid "Could not login with account %(user)s | %(msg)s"
msgstr "アカウント%(user)s ではログインできませんでした |%(msg)s"

#: pyload/plugins/Account.py:86
msgid "Wrong Password"
msgstr "間違ったパスワード"

#: pyload/plugins/Account.py:240
#, python-format
msgid "Your Time %s has wrong format, use: 1:22-3:44"
msgstr ""

#: pyload/plugins/Account.py:266
#, python-format
msgid "Account %s has not enough traffic, checking again in 30min"
msgstr "アカウント %s が十分なトラフィックがない、30 分でもう一度チェック"

#: pyload/plugins/Account.py:273
#, python-format
msgid "Account %s is expired, checking again in 1h"
msgstr "アカウント %s は有効期限が切れて、1 h でもう一度チェック"

#: pyload/plugins/crypter/SerienjunkiesOrg.py:128
msgid "Downloadlimit reached"
msgstr "ダウンロード制限に達しました"

#: pyload/manager/PluginManager.py:153
#, python-format
msgid "%s has a invalid pattern."
msgstr ""

#: pyload/manager/PluginManager.py:272
#, python-format
msgid "Error importing %(name)s: %(msg)s"
msgstr "%(name)s：%(msg)sのインポート エラー"

#: pyload/plugins/internal/MultiHoster.py:133
msgid "No Hoster loaded"
msgstr "ホスティング サービスが読み込まれていません"

#: pyload/plugins/account/BitshareCom.py:37
msgid "Activate direct Download in your Bitshare Account"
msgstr "Bitshare アカウントで直接のダウンロードを有効にします。"

#: pyload/plugins/container/LinkList.py:65
msgid "LinkList could not be cleared."
msgstr ""

#: pyload/manager/AccountManager.py:88
msgid "Account settings deleted, due to new config format."
msgstr ""

#: pyload/plugins/hoster/BasePlugin.py:65
msgid "Authorization required (username:password)"
msgstr " (username:password)承認が必要"

#: pyload/plugins/hoster/SimplydebridCom.py:25
#: pyload/plugins/hoster/RealdebridCom.py:41
#: pyload/plugins/hoster/FreeWayMe.py:38 pyload/plugins/hoster/ZeveraCom.py:22
#: pyload/plugins/hoster/UnrestrictLi.py:53
#: pyload/plugins/hoster/Premium4Me.py:28 pyload/plugins/hoster/FastixRu.py:36
#: pyload/plugins/hoster/AlldebridCom.py:38
#: pyload/plugins/hoster/DebridItaliaCom.py:40
#: pyload/plugins/hoster/RPNetBiz.py:26
#: pyload/plugins/hoster/MultiDebridCom.py:41
#: pyload/plugins/hoster/ReloadCc.py:24 pyload/plugins/hoster/RehostTo.py:26
#: pyload/plugins/hoster/PremiumizeMe.py:22
#: pyload/plugins/addon/RPNetBiz.py:43
#, python-format
msgid "Please enter your %s account or deactivate this plugin"
msgstr "%S アカウントを入力するか、このプラグインを無効にしてください。"

#: pyload/plugins/hoster/FilesMailRu.py:99
#, python-format
msgid "There was HTML Code in the Downloaded File (%s)...redirect error? The Download will be restarted."
msgstr ""

#: pyload/plugins/hoster/NetloadIn.py:146
#: pyload/plugins/hoster/NetloadIn.py:170
msgid "File temporarily not available"
msgstr "ファイルが一時的に利用できません。"

#: pyload/plugins/hoster/NetloadIn.py:183
#, python-format
msgid "Netload: waiting between downloads %d s."
msgstr "Netload: ダウンロード %d 秒間待機しています。"

#: pyload/plugins/hoster/NetloadIn.py:214
#, python-format
msgid "Netload: waiting for captcha %d s."
msgstr "Netload: キャプチャ %d 秒を待っています。"

#: pyload/plugins/hoster/NetloadIn.py:252
msgid "Downloaded File was empty"
msgstr "ダウンロードしたファイルが空だった"

#: pyload/plugins/hoster/UploadedTo.py:129
msgid "API key invalid"
msgstr "API キーが無効です。"

#: pyload/plugins/hoster/UploadedTo.py:153
#, python-format
msgid "%s: Not enough traffic left"
msgstr "%s：十分なトラフィックがない"

#: pyload/plugins/hoster/UploadedTo.py:156
msgid "Traffic exceeded"
msgstr "トラフィックを超えています"

#: pyload/plugins/hoster/RapidshareCom.py:100
msgid "Rapidshare: Traffic Share (direct download)"
msgstr "急流: トラフィックを共有 (ダウンロードによる直販)"

#: pyload/plugins/hoster/RapidshareCom.py:127
#: pyload/plugins/hoster/RapidshareCom.py:194
msgid "Already downloading from this ip address, waiting 60 seconds"
msgstr "既にこの ip アドレスからダウンロードする、60 秒を待っています。"

#: pyload/plugins/hoster/RapidshareCom.py:131
msgid "Invalid Auth Code, download will be restarted"
msgstr "無効な認証コード、ダウンロードが再起動"

#: pyload/plugins/hoster/RapidshareCom.py:199
msgid "RapidShareCom: No free slots"
msgstr "RapidShareCom： 空きスロット"

#: pyload/plugins/hoster/RapidshareCom.py:202
msgid "You need a premium account for this file"
msgstr "このファイルのプレミアム アカウントを必要があります。"

#: pyload/plugins/hoster/RapidshareCom.py:204
msgid "Filename reported invalid"
msgstr "無効なファイル名を報告"

#: pyload/plugins/hoster/FileserveCom.py:99
msgid "Parallel download error, now waiting 60s."
msgstr "並列ダウンロード エラー、60秒を待っています。"

#: pyload/plugins/hoster/FileserveCom.py:215
msgid "Not logged in."
msgstr "ログインしていません。"

#: pyload/plugins/hoster/MegaNz.py:56
msgid "Decryption failed"
msgstr "復号化に失敗しました"

#: pyload/plugins/hoster/MegaNz.py:106
msgid "No file key provided in the URL"
msgstr "URL で提供されるファイル キーがありません。"

#: pyload/plugins/hoster/MegaNz.py:118
msgid "Error code:"
msgstr "エラー コード:"

#: pyload/plugins/Container.py:68
msgid "File not exists."
msgstr ""

#: pyload/plugins/addon/UpdateManager.py:74
msgid "*** Plugins have been updated, please restart pyLoad ***"
msgstr "* * * プラグインが更新されて、pyLoad を再起動してください * * *"

#: pyload/plugins/addon/UpdateManager.py:76
msgid "Plugins updated and reloaded"
msgstr "プラグインの更新し、再読み込み"

#: pyload/plugins/addon/UpdateManager.py:79
msgid "No plugin updates available"
msgstr "プラグインの更新はありません。"

#: pyload/plugins/addon/UpdateManager.py:96
msgid "No Updates for pyLoad"
msgstr "PyLoad の更新"

#: pyload/plugins/addon/UpdateManager.py:100
#, python-format
msgid "***  New pyLoad Version %s available  ***"
msgstr "* * * 新しい pyLoad バージョン %s が利用 * * *"

#: pyload/plugins/addon/UpdateManager.py:101
msgid "***  Get it here: http://pyload.org/download  ***"
msgstr "* * * それを得るここで: http://pyload.org/download * * *"

#: pyload/plugins/addon/UpdateManager.py:104
msgid "Not able to connect server for updates"
msgstr "更新サーバーに接続することはできません。"

#: pyload/plugins/addon/UpdateManager.py:148
#, python-format
msgid "New version of %(type)s|%(name)s : %(version).2f"
msgstr "新しいバージョンの%(type)s|%(name)s%(version) .2f"

#: pyload/plugins/addon/UpdateManager.py:157
#: pyload/plugins/addon/UpdateManager.py:162
#, python-format
msgid "Error when updating %s"
msgstr "%sを更新するときのエラー"

#: pyload/plugins/addon/UpdateManager.py:162
msgid "Version mismatch"
msgstr "バージョンの不一致"

#: pyload/plugins/addon/IRCInterface.py:82
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s "
msgstr "ダウンロード完了: %(name)s @ %(plugin)s"

#: pyload/plugins/addon/IRCInterface.py:95
#, python-format
msgid "New Captcha Request: %s"
msgstr "新しいキャプチャ要求: %s"

#: pyload/plugins/addon/IRCInterface.py:96
#, python-format
msgid "Answer with 'c %s text on the captcha'"
msgstr "'C %s テキストのキャプチャを' と答え"

#: pyload/plugins/addon/Premium4Me.py:29
msgid "Please add your premium.to account first and restart pyLoad"
msgstr ""

#: pyload/plugins/addon/HotFolder.py:82
#, python-format
msgid "Added %s from HotFolder"
msgstr "HotFolder から%s追加 "

#: pyload/plugins/addon/ExtractArchive.py:95
#, python-format
msgid "No %s installed"
msgstr "%s がインストールされました"

#: pyload/plugins/addon/ExtractArchive.py:97
#: pyload/plugins/addon/ExtractArchive.py:102
#, python-format
msgid "Could not activate %s"
msgstr "%S をアクティブにできませんでした。"

#: pyload/plugins/addon/ExtractArchive.py:107
msgid "Activated"
msgstr "アクティブ化"

#: pyload/plugins/addon/ExtractArchive.py:109
msgid "No Extract plugins activated"
msgstr "アクティブ化のプラグインがない"

#: pyload/plugins/addon/ExtractArchive.py:121
#, python-format
msgid "Package %s queued for later extracting"
msgstr "パッケージ %s は、抽出後のキュー"

#: pyload/plugins/addon/ExtractArchive.py:144
#, python-format
msgid "Check package %s"
msgstr "パッケージ %s をチェック"

#: pyload/plugins/addon/ExtractArchive.py:185
#, python-format
msgid "Extract to %s"
msgstr "%S を抽出します。"

#: pyload/plugins/addon/ExtractArchive.py:200
msgid "No files found to extract"
msgstr "ファイルを抽出するが見つかりません"

#: pyload/plugins/addon/ExtractArchive.py:207
msgid "extracting"
msgstr "展開中"

#: pyload/plugins/addon/ExtractArchive.py:218
msgid "Password protected"
msgstr "パスワードで保護されています"

#: pyload/plugins/addon/ExtractArchive.py:239
msgid "Wrong password"
msgstr "正しくないパスワード"

#: pyload/plugins/addon/ExtractArchive.py:247
#, python-format
msgid "Deleting %s files"
msgstr "%s 個のファイルを削除中"

#: pyload/plugins/addon/ExtractArchive.py:254
msgid "Extracting finished"
msgstr "展開が完了しました"

#: pyload/plugins/addon/ExtractArchive.py:260
msgid "Archive Error"
msgstr "アーカイブ エラー"

#: pyload/plugins/addon/ExtractArchive.py:262
msgid "CRC Mismatch"
msgstr "CRC が不一致"

#: pyload/plugins/addon/ExtractArchive.py:266
msgid "Unknown Error"
msgstr "不明なエラー"

#: pyload/plugins/addon/ExtractArchive.py:318
msgid "Setting User and Group failed"
msgstr "ユーザー設定およびグループに失敗しました"

#: pyload/plugins/addon/ClickAndLoad.py:75
msgid "Click'N'Load: Port 9666 already in use"
msgstr "Click'N'Load: 使用中のポート 9666"

#: pyload/plugins/addon/CaptchaTrader.py:69
#: pyload/plugins/addon/Captcha9kw.py:59
#: pyload/plugins/addon/ExpertDecoders.py:50
#, python-format
msgid "%s credits left"
msgstr "%s のクレジットを左"

#: pyload/plugins/addon/CaptchaTrader.py:117
msgid "Could not send response."
msgstr "応答を送信できませんでした。"

#: pyload/plugins/addon/CaptchaTrader.py:135
msgid "Your CaptchaTrader Account has not enough credits"
msgstr "あなたの CaptchaTrader アカウントが十分なクレジット"

#: pyload/plugins/addon/LinkdecrypterCom.py:43
msgid "Crypter list not found"
msgstr "Crypter リストが見つかりません"

#: pyload/plugins/addon/LinkdecrypterCom.py:57
msgid "Crypter list is empty"
msgstr "Crypter リストは空です。"

#: pyload/plugins/addon/XMPPInterface.py:91
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s"
msgstr "ダウンロード完了: %(name)s @ %(plugin)s"

#: pyload/plugins/addon/Captcha9kw.py:93
#, python-format
msgid "New CaptchaID from upload: %s : %s"
msgstr "アップロードから新しい CaptchaID: %s: %s"

#: pyload/plugins/addon/Captcha9kw.py:129
msgid "Your Captcha 9kw.eu Account has not enough credits"
msgstr "あなたのキャプチャ 9kw.eu アカウントが十分なクレジット"

#: pyload/plugins/addon/ExternalScripts.py:54
#, python-format
msgid "Installed scripts for %s: "
msgstr "%s のインストール スクリプト"

#: pyload/plugins/addon/ExternalScripts.py:69
msgid "Script not executable:"
msgstr "スクリプトがない実行可能ファイル:"

#: pyload/plugins/addon/ExternalScripts.py:80
#, python-format
msgid "Error in %(script)s: %(error)s"
msgstr "%(script)s のエラー：%(error)s"

#: pyload/plugins/addon/ExpertDecoders.py:95
msgid "Your ExpertDecoders Account has not enough credits"
msgstr "あなたの ExpertDecoders アカウントが十分なクレジット"

#: pyload/plugins/addon/RehostTo.py:32
msgid "Please add your rehost.to account first and restart pyLoad"
msgstr "まず、rehost.to アカウントを追加し、pyLoad を再起動してください。"

#: pyload/plugins/addon/PremiumizeMe.py:48
msgid "Please add a valid premiumize.me account first and restart pyLoad."
msgstr ""

#: pyload/plugins/addon/CaptchaBrotherhood.py:69
#, python-format
msgid "%d credits left"
msgstr "%d のクレジットを残った"

#: pyload/plugins/Base.py:389
msgid "Pil and tesseract not installed and no Client connected for captcha decrypting"
msgstr "Pil とテッセラクト インストールされていないクライアント接続 captcha 解読"

#: pyload/plugins/Base.py:393
msgid "No captcha result obtained in appropiate time by any of the plugins."
msgstr ""

#: pyload/plugins/Base.py:498 pyload/plugins/Base.py:532
#, python-format
msgid "Setting User and Group failed: %s"
msgstr "ユーザーとグループの設定に失敗しました: %s"

#: pyload/manager/CaptchaManager.py:78
msgid "No Client connected for captcha decrypting"
msgstr ""

#: pyload/Api.py:330
#, python-format
msgid "Added package %(name)s containing %(count)d links"
msgstr ""

#: pyload/Api.py:593
#, python-format
msgid "Added %(count)d links to package #%(package)d "
msgstr ""

#: pyload/utils/JsEngine.py:156
msgid "No js engine detected, please install either Spidermonkey, ossp-js, pyv8 or rhino"
msgstr ""

