msgid ""
msgstr "Project-Id-Version: pyload\n"
"Report-Msgid-Bugs-To: 'bugs@pyload.org'\n"
"POT-Creation-Date: 2014-04-08 15:01+0200\n"
"PO-Revision-Date: 2014-04-09 05:39-0400\n"
"Last-Translator: pyloadTeam <team@pyload.org>\n"
"Language-Team: Russian\n"
"Language: ru_RU\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"X-Generator: crowdin.net\n"

#: module/Core.py:182
msgid "Received Quit signal"
msgstr "Получен сигнал для завершения работы"

#: module/Core.py:303
#, python-format
msgid "pyLoad already running with pid %s"
msgstr "pyLoad уже запущен, pid %s"

#: module/Core.py:317
#, python-format
msgid "Failed changing group: %s"
msgstr "Не удалось изменить группу: %s"

#: module/Core.py:327
#, python-format
msgid "Failed changing user: %s"
msgstr "Не удалось изменить пользователя: %s"

#: module/Core.py:329
msgid "folder for logs"
msgstr "папка отчетов"

#: module/Core.py:340
msgid "Starting"
msgstr "Запускается"

#: module/Core.py:341
#, python-format
msgid "Using home directory: %s"
msgstr "Основная папка: %s"

#: module/Core.py:350
msgid "pycrypto to decode container files"
msgstr "pycrypto для декодирования файлов контейнеров"

#: module/Core.py:353
msgid "folder for temporary files"
msgstr "папка временных файлов"

#: module/Core.py:358
msgid "folder for downloads"
msgstr "папка для закачек"

#: module/Core.py:361
msgid "OpenSSL for secure connection"
msgstr "OpenSSL для безопасного соединения"

#: module/Core.py:365
msgid "Moving old user config to DB"
msgstr "Переместить прежнюю пользовательскую конфигурацию в БД"

#: module/Core.py:368
msgid "Please check your logindata with ./pyload.py -u"
msgstr "Пожалуйста, проверьте свои учётные данные запустив ./pyload.py -u"

#: module/Core.py:371
msgid "All links removed"
msgstr "Все ссылки удалены"

#: module/Core.py:402
#, python-format
msgid "Downloadtime: %s"
msgstr "Время закачки: %s"

#: module/Core.py:412
#, python-format
msgid "Free space: %s"
msgstr "Свободное место: %s"

#: module/Core.py:432
msgid "Activating Accounts..."
msgstr "Активация аккаунта..."

#: module/Core.py:438
msgid "Activating Plugins..."
msgstr "Активация плагина..."

#: module/Core.py:441
msgid "pyLoad is up and running"
msgstr "pyLoad загружен и работает"

#: module/Core.py:460
msgid "restarting pyLoad"
msgstr "перезапуск pyLoad"

#: module/Core.py:464
msgid "pyLoad quits"
msgstr "завершение работы pyLoad"

#: module/Core.py:521
#, python-format
msgid "Install %s"
msgstr "Установка %s"

#: module/Core.py:557
#, python-format
msgid "could not find %(desc)s: %(name)s"
msgstr "не могу найти %(desc)s: %(name)s"

#: module/Core.py:559
#, python-format
msgid "could not create %(desc)s: %(name)s"
msgstr "не могу создать %(desc)s: %(name)s"

#: module/Core.py:580
msgid "shutting down..."
msgstr "завершение работы..."

#: module/Core.py:597
msgid "error while shutting down"
msgstr "ошибка при завершении работы"

#: module/Core.py:661
msgid "killed pyLoad from Terminal"
msgstr "pyLoad остановлен с терминала"

#: module/database/DatabaseBackend.py:174
msgid "Filedatabase was deleted due to incompatible version."
msgstr "Базы данных была удалена по причине несовместимой версии."

#: module/database/DatabaseBackend.py:189
msgid "Filedatabase could NOT be converted."
msgstr "База данных НЕ может быть преобразована."

#: module/database/DatabaseBackend.py:198
msgid "Database was converted from v2 to v3."
msgstr "База данных преобразована из v2 в v3."

#: module/database/DatabaseBackend.py:206
msgid "Database was converted from v3 to v4."
msgstr "База данных преобразована из v2 в v3."

#: module/database/DatabaseBackend.py:252
msgid "Converting old Django DB"
msgstr "Преобразование прежней БД Django"

#: module/database/FileDatabase.py:45
msgid "finished"
msgstr "закончено"

#: module/database/FileDatabase.py:45
msgid "offline"
msgstr "оф-лайн"

#: module/database/FileDatabase.py:45
msgid "online"
msgstr "он-лайн"

#: module/database/FileDatabase.py:45
msgid "queued"
msgstr "в очереди"

#: module/database/FileDatabase.py:45
msgid "skipped"
msgstr "пропущено"

#: module/database/FileDatabase.py:45
msgid "waiting"
msgstr "ожидание"

#: module/database/FileDatabase.py:45
msgid "temp. offline"
msgstr "временно недоступно"

#: module/database/FileDatabase.py:45
msgid "starting"
msgstr "запускается"

#: module/database/FileDatabase.py:45
msgid "failed"
msgstr "завершено с ошибкой"

#: module/database/FileDatabase.py:45
msgid "aborted"
msgstr "прервано"

#: module/database/FileDatabase.py:45
msgid "decrypting"
msgstr "раскодирование"

#: module/database/FileDatabase.py:45
msgid "custom"
msgstr "пользовательский"

#: module/database/FileDatabase.py:45
msgid "downloading"
msgstr "загружается"

#: module/database/FileDatabase.py:45
msgid "processing"
msgstr "обрабатывается"

#: module/database/FileDatabase.py:45
msgid "unknown"
msgstr "неизвестно"

#: module/database/FileDatabase.py:531 module/plugins/addon/IRCInterface.py:74
#: module/plugins/addon/XMPPInterface.py:83
#, python-format
msgid "Package finished: %s"
msgstr "Пакет завершен: %s"

#: module/remote/ThriftBackend.py:39
msgid "Using SSL ThriftBackend"
msgstr "Используется SSL ThriftBackend"

#: module/manager/RemoteManager.py:35
#, python-format
msgid "Remote backend error: %s"
msgstr "Ошибка удаленного сервиса: %s"

#: module/manager/RemoteManager.py:82
#, python-format
msgid "Starting %(name)s: %(addr)s:%(port)s"
msgstr "Запуск %(name)s: %(addr)s:%(port)s"

#: module/manager/RemoteManager.py:84
#, python-format
msgid "Failed loading backend %(name)s | %(error)s"
msgstr "Ошибка при загрузке %(name)s | %(error)s"

#: module/web/json_app.py:57
#, python-format
msgid "waiting %s"
msgstr "ожидание %s"

#: module/thread/ServerThread.py:35
msgid "SSL certificates not found."
msgstr "SSL сертификаты не найдены."

#: module/thread/ServerThread.py:39
#, python-format
msgid "Sorry, we dropped support for starting %s directly within pyLoad"
msgstr "К сожалению, поддержка в pyLoad прекращена начиная с версии %s"

#: module/thread/ServerThread.py:40
msgid "You can use the threaded server which offers good performance and ssl,"
msgstr "Вы можете использовать threaded сервер для повышения производительности и использования SSL,"

#: module/thread/ServerThread.py:41
#, python-format
msgid "of course you can still use your existing %s with pyLoads fastcgi server"
msgstr "но можно и использовать прежний сервер %s с pyLoads fastcgi"

#: module/thread/ServerThread.py:42
msgid "sample configs are located in the module/web/servers directory"
msgstr "Примеры конфигурации web-серверов можно посмотреть в папке module/web/servers"

#: module/thread/ServerThread.py:49
#, python-format
msgid "Can't use %(server)s, python-flup is not installed!"
msgstr "Использовать %(server)s невозможно, так как не установлен python-flup!"

#: module/thread/ServerThread.py:56
#, python-format
msgid "Error importing lightweight server: %s"
msgstr ""

#: module/thread/ServerThread.py:57
msgid "You need to download and compile bjoern, https://github.com/jonashaag/bjoern"
msgstr ""

#: module/thread/ServerThread.py:58
msgid "Copy the boern.so to module/lib folder or use Setup.py install"
msgstr ""

#: module/thread/ServerThread.py:59
msgid "Of course you need to be familiar with linux and know how to compile software"
msgstr ""

#: module/thread/ServerThread.py:63
msgid "Server set to threaded, due to known performance problems on windows."
msgstr ""

#: module/thread/ServerThread.py:80 module/thread/ServerThread.py:103
msgid "This server offers no SSL, please consider using threaded instead"
msgstr "Этот сервер не предоставляет возможность использовать SSL, пожалуйста рассмотрите возможность использовать сервер threaded взамен выбранного"

#: module/thread/ServerThread.py:82
#, python-format
msgid "Starting builtin webserver: %(host)s:%(port)d"
msgstr "Запуск встроенного веб-сервера django: %(host)s:%(port)d"

#: module/thread/ServerThread.py:87
#, python-format
msgid "Starting threaded SSL webserver: %(host)s:%(port)d"
msgstr "Запуск веб-сервера lighttpd: %(host)s:%(port)d"

#: module/thread/ServerThread.py:91
#, python-format
msgid "Starting threaded webserver: %(host)s:%(port)d"
msgstr "Запуск threaded веб-сервера: %(host)s:%(port)d"

#: module/thread/ServerThread.py:97
#, python-format
msgid "Starting fastcgi server: %(host)s:%(port)d"
msgstr "Запуск fastcgi-сервера: %(host)s:%(port)d"

#: module/thread/ServerThread.py:105
#, python-format
msgid "Starting lightweight webserver (bjoern): %(host)s:%(port)d"
msgstr ""

#: module/web/pyload_app.py:125
msgid "You dont have permission to access this page."
msgstr "У вас нет прав на просмотр страницы."

#: module/web/pyload_app.py:193
msgid "Download directory not found."
msgstr "Папка для закачек не найдена."

#: module/web/pyload_app.py:260 module/web/pyload_app.py:267
msgid "unlimited"
msgstr "неограниченный"

#: module/web/pyload_app.py:262 module/web/pyload_app.py:269
msgid "not available"
msgstr "не доступно"

#: module/web/pyload_app.py:508
msgid "Run pyload.py -s to access the setup."
msgstr "Для доступа к настройкам запустите pyload.py -s."

#: module/network/HTTPDownload.py:245
#, python-format
msgid "Download chunks failed, fallback to single connection | %s"
msgstr "Загрузка параллельных потоков данных завершена с ошибками, возврат к однопоточной загрузке | %s"

#: module/thread/PluginThread.py:183
#, python-format
msgid "Download starts: %s"
msgstr "Загрузка начата: %s"

#: module/thread/PluginThread.py:189
#, python-format
msgid "Download finished: %s"
msgstr "Загрузка завершена: %s"

#: module/thread/PluginThread.py:194 module/thread/PluginThread.py:365
#, python-format
msgid "Plugin %s is missing a function."
msgstr "В плагине %s нет функции."

#: module/thread/PluginThread.py:202 module/thread/PluginThread.py:265
#: module/thread/PluginThread.py:382
#, python-format
msgid "Download aborted: %s"
msgstr "Загрузка прервана: %s"

#: module/thread/PluginThread.py:222
#, python-format
msgid "Download restarted: %(name)s | %(msg)s"
msgstr "Ошибка загрузки: %(name)s | %(msg)s"

#: module/thread/PluginThread.py:231 module/thread/PluginThread.py:373
#, python-format
msgid "Download is offline: %s"
msgstr "Загрузка недоступна: %s"

#: module/thread/PluginThread.py:234
#, python-format
msgid "Download is temporary offline: %s"
msgstr "Загрузка временно недоступна: %s"

#: module/thread/PluginThread.py:237 module/thread/PluginThread.py:304
#, python-format
msgid "Download failed: %(name)s | %(msg)s"
msgstr "Ошибка загрузки: %(name)s | %(msg)s"

#: module/thread/PluginThread.py:254
msgid "Couldn't connect to host or connection reset, waiting 1 minute and retry."
msgstr "Невозможно соединиться с провайдером или срыв соединения, следующая попытка через одну минуту."

#: module/thread/PluginThread.py:290
#, python-format
msgid "Download skipped: %(name)s due to %(plugin)s"
msgstr "Загрузка пропущена: %(name)s @ %(plugin)s"

#: module/thread/PluginThread.py:361
#, python-format
msgid "Decrypting starts: %s"
msgstr "Декодирование начато: %s"

#: module/thread/PluginThread.py:376 module/thread/PluginThread.py:394
#, python-format
msgid "Decrypting failed: %(name)s | %(msg)s"
msgstr "Ошибка декодирования: %(name)s | %(msg)s"

#: module/thread/PluginThread.py:388
#, python-format
msgid "Retrying %s"
msgstr "Повторная попытка %s"

#: module/thread/PluginThread.py:635
#, python-format
msgid "Info Fetching for %(name)s failed | %(err)s"
msgstr "Получение информации по %(name)s завершилось ошибкой | %(err)s"

#: module/manager/AddonManager.py:90 module/plugins/Addon.py:102
#, python-format
msgid "Error executing addon: %s"
msgstr "Ощибка выполнения захватов: %s"

#: module/manager/AddonManager.py:140
#, python-format
msgid "Failed activating %(name)s"
msgstr "Ошибка активации %(name)s"

#: module/manager/AddonManager.py:144
#, python-format
msgid "Activated plugins: %s"
msgstr ""

#: module/manager/AddonManager.py:145
#, python-format
msgid "Deactivate plugins: %s"
msgstr ""

#: module/manager/ThreadManager.py:137
#, python-format
msgid "Reconnect Failed: %s"
msgstr "Переподключение не удалось: %s"

#: module/manager/ThreadManager.py:176
msgid "Reconnect script not found!"
msgstr "Скрипт переподключения не найден!"

#: module/manager/ThreadManager.py:182
msgid "Starting reconnect"
msgstr "Начинаем переподключение"

#: module/manager/ThreadManager.py:196
msgid "Failed executing reconnect script!"
msgstr "Ошибка при выполнении скрипта переподключения"

#: module/manager/ThreadManager.py:208
#, python-format
msgid "Reconnected, new IP: %s"
msgstr "Переподключено, новый IP: %s"

#: module/manager/ThreadManager.py:288
msgid "Not enough space left on device"
msgstr "Не хватает места на устройстве."

#: module/plugins/Account.py:85 module/plugins/Account.py:91
#, python-format
msgid "Could not login with account %(user)s | %(msg)s"
msgstr "Не могу войти с учетной записью %(user)s | %(msg)s"

#: module/plugins/Account.py:86
msgid "Wrong Password"
msgstr "Неправильный пароль"

#: module/plugins/Account.py:240
#, python-format
msgid "Your Time %s has wrong format, use: 1:22-3:44"
msgstr "Время %s имеет неправильный формат, используйте формат 1:22-3:44"

#: module/plugins/Account.py:266
#, python-format
msgid "Account %s has not enough traffic, checking again in 30min"
msgstr "Недостаточно траффика в аккаунте %s, следующая проверка через 30 минут"

#: module/plugins/Account.py:273
#, python-format
msgid "Account %s is expired, checking again in 1h"
msgstr "Истек срок действия аккаунта %s, следующая проверка через 1 час"

#: module/plugins/crypter/SerienjunkiesOrg.py:128
msgid "Downloadlimit reached"
msgstr "Достигнут лимит загрузок"

#: module/manager/PluginManager.py:153
#, python-format
msgid "%s has a invalid pattern."
msgstr "%s имеет не правильный шаблон."

#: module/manager/PluginManager.py:272
#, python-format
msgid "Error importing %(name)s: %(msg)s"
msgstr "Ошибка импорта %(name)s: %(msg)s"

#: module/plugins/internal/MultiHoster.py:133
msgid "No Hoster loaded"
msgstr "Не загружен ни один из файлобменников"

#: module/plugins/account/BitshareCom.py:37
msgid "Activate direct Download in your Bitshare Account"
msgstr "В своей учётной записи включите опцию 'direct Download'"

#: module/plugins/container/LinkList.py:65
msgid "LinkList could not be cleared."
msgstr "Список ссылок не может быть очищен."

#: module/manager/AccountManager.py:88
msgid "Account settings deleted, due to new config format."
msgstr "Установки учетной записи удалены в связи с новым форматом."

#: module/plugins/hoster/BasePlugin.py:65
msgid "Authorization required (username:password)"
msgstr "Необходима авторизация (имя пользователя:пароль)"

#: module/plugins/hoster/SimplydebridCom.py:25
#: module/plugins/hoster/RealdebridCom.py:41
#: module/plugins/hoster/FreeWayMe.py:38 module/plugins/hoster/ZeveraCom.py:22
#: module/plugins/hoster/UnrestrictLi.py:53
#: module/plugins/hoster/Premium4Me.py:28 module/plugins/hoster/FastixRu.py:36
#: module/plugins/hoster/AlldebridCom.py:38
#: module/plugins/hoster/DebridItaliaCom.py:40
#: module/plugins/hoster/RPNetBiz.py:26
#: module/plugins/hoster/MultiDebridCom.py:41
#: module/plugins/hoster/ReloadCc.py:24 module/plugins/hoster/RehostTo.py:26
#: module/plugins/hoster/PremiumizeMe.py:22
#: module/plugins/addon/RPNetBiz.py:43
#, python-format
msgid "Please enter your %s account or deactivate this plugin"
msgstr "Пожалуйста, введите ваш аккаунт для %s или отключить этот плагин"

#: module/plugins/hoster/FilesMailRu.py:99
#, python-format
msgid "There was HTML Code in the Downloaded File (%s)...redirect error? The Download will be restarted."
msgstr "Найден HTML-код в файле загрузки (%s)... ошибка перенаправления? Загрузка будет перезапущена."

#: module/plugins/hoster/NetloadIn.py:146
#: module/plugins/hoster/NetloadIn.py:170
msgid "File temporarily not available"
msgstr "Файл временно недоступен"

#: module/plugins/hoster/NetloadIn.py:183
#, python-format
msgid "Netload: waiting between downloads %d s."
msgstr "Netload: ожидание между загрузками %d сек."

#: module/plugins/hoster/NetloadIn.py:214
#, python-format
msgid "Netload: waiting for captcha %d s."
msgstr "Netload: ожидание картинки %d сек."

#: module/plugins/hoster/NetloadIn.py:252
msgid "Downloaded File was empty"
msgstr "Загруженный файл пуст"

#: module/plugins/hoster/UploadedTo.py:129
msgid "API key invalid"
msgstr "Неверный ключ API"

#: module/plugins/hoster/UploadedTo.py:153
#, python-format
msgid "%s: Not enough traffic left"
msgstr "%s: Осталось недостаточно трафика"

#: module/plugins/hoster/UploadedTo.py:156
msgid "Traffic exceeded"
msgstr "Трафик закончился"

#: module/plugins/hoster/RapidshareCom.py:100
msgid "Rapidshare: Traffic Share (direct download)"
msgstr "Rapidshare: Traffic Share (прямая загрузка)"

#: module/plugins/hoster/RapidshareCom.py:127
#: module/plugins/hoster/RapidshareCom.py:194
msgid "Already downloading from this ip address, waiting 60 seconds"
msgstr "Уже идет загрузка с этого IP, ждем 60 секунд"

#: module/plugins/hoster/RapidshareCom.py:131
msgid "Invalid Auth Code, download will be restarted"
msgstr "Неправильный код идентификации, загрузка будет перезапущена"

#: module/plugins/hoster/RapidshareCom.py:199
msgid "RapidShareCom: No free slots"
msgstr "RapidShareCom: Нет свободного слота"

#: module/plugins/hoster/RapidshareCom.py:202
msgid "You need a premium account for this file"
msgstr "Для этого файла нужен премиум аккаунт"

#: module/plugins/hoster/RapidshareCom.py:204
msgid "Filename reported invalid"
msgstr "Имя файла указано неверно"

#: module/plugins/hoster/FileserveCom.py:99
msgid "Parallel download error, now waiting 60s."
msgstr "Ошибка параллельной загрузки, ждем 60 секунд."

#: module/plugins/hoster/FileserveCom.py:215
msgid "Not logged in."
msgstr "Вход не произведен."

#: module/plugins/hoster/MegaNz.py:56
msgid "Decryption failed"
msgstr "Сбой расшифровки"

#: module/plugins/hoster/MegaNz.py:106
msgid "No file key provided in the URL"
msgstr "Нет ключа файла в URL-адресе"

#: module/plugins/hoster/MegaNz.py:118
msgid "Error code:"
msgstr "Код ошибки:"

#: module/plugins/Container.py:68
msgid "File not exists."
msgstr "Файл не существует."

#: module/plugins/addon/UpdateManager.py:74
msgid "*** Plugins have been updated, please restart pyLoad ***"
msgstr "*** Дополнения обновлены, перезапустите pyLoad ***"

#: module/plugins/addon/UpdateManager.py:76
msgid "Plugins updated and reloaded"
msgstr "Дополнения обновлены и перезагружены"

#: module/plugins/addon/UpdateManager.py:79
msgid "No plugin updates available"
msgstr "Нет обновлений для дополнений"

#: module/plugins/addon/UpdateManager.py:96
msgid "No Updates for pyLoad"
msgstr "Нет обновлений pyLoad"

#: module/plugins/addon/UpdateManager.py:100
#, python-format
msgid "***  New pyLoad Version %s available  ***"
msgstr "***  Доступна новая версия pyLoad %s  ***"

#: module/plugins/addon/UpdateManager.py:101
msgid "***  Get it here: http://pyload.org/download  ***"
msgstr "***  Скачайте здесь: http://pyload.org/download  ***"

#: module/plugins/addon/UpdateManager.py:104
msgid "Not able to connect server for updates"
msgstr "Не возможно соединиться с сервером обновлений"

#: module/plugins/addon/UpdateManager.py:148
#, python-format
msgid "New version of %(type)s|%(name)s : %(version).2f"
msgstr "Новая версия %(type)s|%(name)s : %(version).2f"

#: module/plugins/addon/UpdateManager.py:157
#: module/plugins/addon/UpdateManager.py:162
#, python-format
msgid "Error when updating %s"
msgstr "Ошибка при обновлении %s"

#: module/plugins/addon/UpdateManager.py:162
msgid "Version mismatch"
msgstr "Конфликт версии"

#: module/plugins/addon/IRCInterface.py:82
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s "
msgstr "Загрузка завершена: %(name)s @ %(plugin)s "

#: module/plugins/addon/IRCInterface.py:95
#, python-format
msgid "New Captcha Request: %s"
msgstr "Новый запрос картинки: %s"

#: module/plugins/addon/IRCInterface.py:96
#, python-format
msgid "Answer with 'c %s text on the captcha'"
msgstr "Ответ с текстом на картинке %s"

#: module/plugins/addon/Premium4Me.py:29
msgid "Please add your premium.to account first and restart pyLoad"
msgstr "Пожалуйста, сначала добавьте учетную запись premium.to и перезапустите pyLoad"

#: module/plugins/addon/HotFolder.py:82
#, python-format
msgid "Added %s from HotFolder"
msgstr "Добавлен %s из HotFolder"

#: module/plugins/addon/ExtractArchive.py:95
#, python-format
msgid "No %s installed"
msgstr "%s не установлен"

#: module/plugins/addon/ExtractArchive.py:97
#: module/plugins/addon/ExtractArchive.py:102
#, python-format
msgid "Could not activate %s"
msgstr "Не возможно активировать %s"

#: module/plugins/addon/ExtractArchive.py:107
msgid "Activated"
msgstr "Активирован(a/о)"

#: module/plugins/addon/ExtractArchive.py:109
msgid "No Extract plugins activated"
msgstr "Не активировано дополнений для извлечения/распаковки"

#: module/plugins/addon/ExtractArchive.py:121
#, python-format
msgid "Package %s queued for later extracting"
msgstr "Пакет %s поставлен в очередь для последующего извлечения/распаковки"

#: module/plugins/addon/ExtractArchive.py:144
#, python-format
msgid "Check package %s"
msgstr "Проверка пакета %s"

#: module/plugins/addon/ExtractArchive.py:185
#, python-format
msgid "Extract to %s"
msgstr "Извлечение/распаковка в %s"

#: module/plugins/addon/ExtractArchive.py:200
msgid "No files found to extract"
msgstr "Не найдено файлов для извлечения"

#: module/plugins/addon/ExtractArchive.py:207
msgid "extracting"
msgstr "извлекается/распаковывается"

#: module/plugins/addon/ExtractArchive.py:218
msgid "Password protected"
msgstr "Защищено паролем"

#: module/plugins/addon/ExtractArchive.py:239
msgid "Wrong password"
msgstr "Неправильный пароль"

#: module/plugins/addon/ExtractArchive.py:247
#, python-format
msgid "Deleting %s files"
msgstr "Удаление файлов %s"

#: module/plugins/addon/ExtractArchive.py:254
msgid "Extracting finished"
msgstr "Извлечениe/распаковка завершено(a)"

#: module/plugins/addon/ExtractArchive.py:260
msgid "Archive Error"
msgstr "Ошибка архива"

#: module/plugins/addon/ExtractArchive.py:262
msgid "CRC Mismatch"
msgstr "Ошибка контрольной суммы"

#: module/plugins/addon/ExtractArchive.py:266
msgid "Unknown Error"
msgstr "Неизвестная ошибка"

#: module/plugins/addon/ExtractArchive.py:318
msgid "Setting User and Group failed"
msgstr "Ошибка установки пользователя и группы: %s"

#: module/plugins/addon/ClickAndLoad.py:75
msgid "Click'N'Load: Port 9666 already in use"
msgstr "Click'N'Load: Порт 9666 уже занят"

#: module/plugins/addon/CaptchaTrader.py:69
#: module/plugins/addon/Captcha9kw.py:59
#: module/plugins/addon/ExpertDecoders.py:50
#, python-format
msgid "%s credits left"
msgstr "Осталось %s кредитов"

#: module/plugins/addon/CaptchaTrader.py:117
msgid "Could not send response."
msgstr "Не удалось отправить ответ."

#: module/plugins/addon/CaptchaTrader.py:135
msgid "Your CaptchaTrader Account has not enough credits"
msgstr "Недостаточно средств на вашем аккаунте CaptchaTrader"

#: module/plugins/addon/LinkdecrypterCom.py:43
msgid "Crypter list not found"
msgstr "Список шифрования не найден"

#: module/plugins/addon/LinkdecrypterCom.py:57
msgid "Crypter list is empty"
msgstr "Список шифрования пуст"

#: module/plugins/addon/XMPPInterface.py:91
#, python-format
msgid "Download finished: %(name)s @ %(plugin)s"
msgstr "Загрузка завершена: %(name)s @ %(plugin)s"

#: module/plugins/addon/Captcha9kw.py:93
#, python-format
msgid "New CaptchaID from upload: %s : %s"
msgstr "Новая(ые) CaptchaID из загрузки: %s: %s"

#: module/plugins/addon/Captcha9kw.py:129
msgid "Your Captcha 9kw.eu Account has not enough credits"
msgstr "Ваша учетная запись 9kw.eu имеет не достаточно кредитов"

#: module/plugins/addon/ExternalScripts.py:54
#, python-format
msgid "Installed scripts for %s: "
msgstr "Установленные скрипты для %s: "

#: module/plugins/addon/ExternalScripts.py:69
msgid "Script not executable:"
msgstr "Не возможно запустить скрипт:"

#: module/plugins/addon/ExternalScripts.py:80
#, python-format
msgid "Error in %(script)s: %(error)s"
msgstr "Ошибка в %(script): %(error)s"

#: module/plugins/addon/ExpertDecoders.py:95
msgid "Your ExpertDecoders Account has not enough credits"
msgstr "Учетная запись ExpertDecoders не имеет достаточно кредитов"

#: module/plugins/addon/RehostTo.py:32
msgid "Please add your rehost.to account first and restart pyLoad"
msgstr "Пожалуйста сначала добавьте ваш rehost.to аккаунт и перезапустите pyLoad"

#: module/plugins/addon/PremiumizeMe.py:48
msgid "Please add a valid premiumize.me account first and restart pyLoad."
msgstr "Пожалуйста сначала добавьте действительную учетную запись для premiumize.me и перезапустить pyLoad."

#: module/plugins/addon/CaptchaBrotherhood.py:69
#, python-format
msgid "%d credits left"
msgstr "Осталось %s кредитов"

#: module/plugins/Base.py:389
msgid "Pil and tesseract not installed and no Client connected for captcha decrypting"
msgstr "Pil и tesseract не установлены. Не подключен клиент для расшифровки картинок"

#: module/plugins/Base.py:393
msgid "No captcha result obtained in appropiate time by any of the plugins."
msgstr "Не получен результат расшифровки картинки в течение отведённого времени ни одним из дополнений"

#: module/plugins/Base.py:498 module/plugins/Base.py:532
#, python-format
msgid "Setting User and Group failed: %s"
msgstr "Ошибка установки пользователя и группы: %s"

#: module/manager/CaptchaManager.py:78
msgid "No Client connected for captcha decrypting"
msgstr "Не подключен клиент для расшифровки картинок"

#: module/Api.py:330
#, python-format
msgid "Added package %(name)s containing %(count)d links"
msgstr "Добавлен контейнер %(name)s с %(count)d сылками"

#: module/Api.py:593
#, python-format
msgid "Added %(count)d links to package #%(package)d "
msgstr "Добавлено %(count)d ссылок в контейнер #%(package)d "

#: module/utils/JsEngine.py:156
msgid "No js engine detected, please install either Spidermonkey, ossp-js, pyv8 or rhino"
msgstr "Не обнаружена js платформа, пожалуйста установите либо Spidermonkey, ossp-js, pyv8 или rhino"

